image: python:3.8-bullseye
port: 8000
command:
  - /bin/sh
  - '-c'
  - |
    cd /opt/repos/repo
    pip install -r requirements.txt
    python app.py
repositories:
  dataset: dsqs9eobxeojxu1
resources:
  replicas: 1
  instanceType: C5
